
import streamlit as st
st.set_page_config(page_title="QuLab", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab")
st.divider()
st.markdown("""
In this lab, we delve into the intricate world of **Loss Given Default (LGD) models**, a critical component of credit risk management. LGD represents the proportion of an exposure that is lost when a borrower defaults, after considering recoveries.

### Understanding LGD Models

We will explore two primary approaches to LGD modeling:

*   **Through-The-Cycle (TTC) LGD:** This approach aims to estimate the long-run average LGD, typically ignoring short-term economic fluctuations. It reflects the inherent loss characteristics of a portfolio over an entire economic cycle.

*   **Point-In-Time (PIT) LGD:** In contrast, PIT LGD models are sensitive to current economic conditions and macroeconomic factors. They provide a more dynamic view of potential losses, adjusting the TTC LGD based on the prevailing economic climate.

### Learning Objectives

Through this interactive application, you will:

*   **Understand Components:** Grasp the fundamental elements of both TTC and PIT LGD models.
*   **Data Proficiency:** Develop practical skills in extracting, cleaning, and engineering features from raw loan data for credit risk modeling.
*   **Statistical Application:** Apply various statistical modeling techniques to accurately estimate LGD values.
*   **Macroeconomic Integration:** Learn how to effectively incorporate macroeconomic factors to enhance the predictive power of LGD models.
*   **Model Evaluation & Deployment:** Understand how to evaluate model performance rigorously and prepare model artifacts for seamless deployment.

### Mathematical Foundations

LGD is often calculated as:

$$LGD = 1 - \frac{Recoveries}{Exposure \ at \ Default \ (EAD)}$$

Where:

*   **Recoveries** are the amounts recouped from a defaulted loan.
*   **EAD** is the outstanding balance at the time of default, plus any additional drawdowns up to the point of default.

For more advanced models, especially Beta regression for LGD, the formula for the mean of a Beta-distributed variable $\mu$ is often related to a linear predictor $X\beta$ through a link function, such as the logit link:

$$\text{logit}(\mu) = \ln\left(\frac{\mu}{1-\mu}\right) = X\beta$$

Thus, the predicted LGD $\hat{\mu}$ can be obtained by:

$$\hat{\mu} = \frac{1}{1 + e^{-X\beta}}$$

This application will guide you through each step, from raw data to a fully evaluated and ready-to-deploy LGD model, offering interactive visualizations and real-time feedback.
""")
# Your code starts here
page = st.sidebar.selectbox(label="Navigation", options=["Data Ingestion", "Feature Engineering", "EDA and Segmentation", "TTC Model Building", "PIT Overlay", "Model Evaluation", "Model Export"])
if page == "Data Ingestion":
    from application_pages.page1 import run_page1
    run_page1()
elif page == "Feature Engineering":
    from application_pages.page2 import run_page2
    run_page2()
elif page == "EDA and Segmentation":
    from application_pages.page3 import run_page3
    run_page3()
elif page == "TTC Model Building":
    from application_pages.page4 import run_page4
    run_page4()
elif page == "PIT Overlay":
    from application_pages.page5 import run_page5
    run_page5()
elif page == "Model Evaluation":
    from application_pages.page6 import run_page6
    run_page6()
elif page == "Model Export":
    from application_pages.page7 import run_page7
    run_page7()
# Your code ends


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@qusandbox.com](mailto:info@qusandbox.com)
''')
